# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # taken from Gekkio/mooneye-gb github action
  build_test_roms:
    name: Build test ROMs
    runs-on: ubuntu-latest
    env:
      WLA_DX_REPO: vhelin/wla-dx
      WLA_DX_COMMIT: 92a0c4be17ea5825ae82cb03a9ff73cb2be66db7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Ubuntu package lists
        run: sudo apt update
        if: runner.os == 'Linux'
      - name: Install Ubuntu packages
        run: sudo apt install cmake
      - name: Cache wla-dx
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/wla-dx
          key: ${{ runner.os }}-${{ env.WLA_DX_COMMIT }}-wla-dx
      - name: Build wla-dx
        if: steps.cache.outputs.cache-hit != 'true'
        run: bash .github/install_wla-dx.sh
      - name: Build test ROMs
        run: make -C tests clean all
        env:
          WLA: ~/wla-dx/binaries/wla-gb
          WLALINK: ~/wla-dx/binaries/wlalink
      - name: Persist test ROMs
        uses: actions/upload-artifact@v1
        with:
          name: tests
          path: tests/build
